# Generated by Django 5.2.7 on 2025-10-27 05:10

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='users.boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prix', models.IntegerField()),
                ('unite', models.CharField(max_length=30)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('quantite', models.IntegerField()),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='shop.rayon')),
            ],
        ),
    ]
