# Generated by Django 5.2.7 on 2025-10-27 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0001_initial'),
        ('shop', '__first__'),
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('rate', models.FloatField(default=0.0)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('plat_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_plat', to='e_commerce.menu_plat')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_produit', to='shop.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Attente', 'attente'), ('Préparation', 'préparation'), ('Livraison', 'livraison'), ('Réçu', 'réçu'), ('Annulé', 'annulé')], default='attente', max_length=15)),
                ('heure_de_commande', models.DateTimeField(auto_now_add=True)),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prix_total', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_produits', to=settings.AUTH_USER_MODEL)),
                ('produits', models.ManyToManyField(through='localisation.Commande_Produit', to='shop.produit')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_produits', to='localisation.position')),
            ],
        ),
        migrations.AddField(
            model_name='commande_produit',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_produit', to='localisation.commandeboutique'),
        ),
        migrations.CreateModel(
            name='CommandeRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Attente', 'attente'), ('Préparation', 'préparation'), ('Livraison', 'livraison'), ('Réçu', 'réçu'), ('Annulé', 'annulé')], default='attente', max_length=15)),
                ('heure_de_commande', models.DateTimeField(auto_now_add=True)),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prix_total', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('plats', models.ManyToManyField(related_name='commandes', through='localisation.Commande_Plat', to='e_commerce.menu_plat')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='localisation.position')),
            ],
        ),
        migrations.AddField(
            model_name='commande_plat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_plat', to='localisation.commanderestaurant'),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='localisation.commanderestaurant')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='users.livreur')),
            ],
        ),
    ]
