# Generated by Django 5.1.7 on 2025-10-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_initial'),
        ('localisation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_plat',
            name='plat_commander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_plat', to='e_commerce.restaurant_plat'),
        ),
        migrations.AlterField(
            model_name='commanderestaurant',
            name='plats',
            field=models.ManyToManyField(related_name='commandes', through='localisation.Commande_Plat', to='e_commerce.restaurant_plat'),
        ),
    ]
