# Generated by Django 5.1.7 on 2025-10-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_initial'),
        ('localisation', '0004_alter_commande_plat_plat_commander_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_plat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_plat_set', to='localisation.commanderestaurant'),
        ),
        migrations.AlterField(
            model_name='commande_plat',
            name='plat_commander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_plat_set', to='e_commerce.restaurant_plat'),
        ),
    ]
