# Generated by Django 5.1.7 on 2025-10-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0005_alter_commande_plat_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_plat',
            name='description',
            field=models.TextField(blank=True, default='aucune description'),
        ),
    ]
