# Generated by Django 5.1.7 on 2025-10-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0007_commanderestaurant_restaurant'),
        ('users', '0002_boutique_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeboutique',
            name='boutique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='users.boutique'),
        ),
    ]
