# Generated by Django 4.2.25 on 2025-11-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_boutique_type'),
        ('localisation', '0008_commandeboutique_boutique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivraisonBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='localisation.commandeboutique')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_boutique', to='users.livreur')),
            ],
        ),
    ]
