# Generated by Django 4.2.25 on 2025-11-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0009_livraisonboutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='heure_de_delivrance',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='heure_de_reception',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('Attente', 'attente'), ('En route', 'en route'), ('Livré', 'Livré'), ('Refuser', 'refuser')], default='attente', max_length=15),
        ),
        migrations.AddField(
            model_name='livraisonboutique',
            name='heure_de_delivrance',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='livraisonboutique',
            name='heure_de_reception',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livraisonboutique',
            name='statut',
            field=models.CharField(choices=[('Attente', 'attente'), ('En route', 'en route'), ('Livré', 'Livré'), ('Refuser', 'refuser')], default='attente', max_length=15),
        ),
    ]
