# Generated by Django 4.2.25 on 2025-11-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0010_livraison_heure_de_delivrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('Attente', 'attente'), ('Accepter', 'accepter'), ('En route', 'en route'), ('Livré', 'Livré'), ('Refuser', 'refuser')], default='attente', max_length=15),
        ),
        migrations.AlterField(
            model_name='livraisonboutique',
            name='statut',
            field=models.CharField(choices=[('Attente', 'attente'), ('Accepter', 'accepter'), ('En route', 'en route'), ('Livré', 'Livré'), ('Refuser', 'refuser')], default='attente', max_length=15),
        ),
    ]
