# Generated by Django 4.2.25 on 2025-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0011_alter_livraison_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('attente', 'Attente'), ('accepter', 'Accepter'), ('en route', 'En route'), ('livré', 'Livré'), ('refuser', 'Refuser')], default='attente', max_length=15),
        ),
        migrations.AlterField(
            model_name='livraisonboutique',
            name='statut',
            field=models.CharField(choices=[('attente', 'Attente'), ('accepter', 'Accepter'), ('en route', 'En route'), ('livré', 'Livré'), ('refuser', 'Refuser')], default='attente', max_length=15),
        ),
    ]
