# Generated by Django 4.2.25 on 2025-11-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0012_alter_livraison_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeboutique',
            name='type',
            field=models.CharField(default='boutique', max_length=9),
        ),
        migrations.AddField(
            model_name='commanderestaurant',
            name='type',
            field=models.CharField(default='restaurant', max_length=11),
        ),
    ]
