# Generated by Django 4.2.25 on 2025-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0013_commandeboutique_type_commanderestaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, default='aucune consigne'),
        ),
    ]
