# Generated by Django 4.2.25 on 2025-11-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_boutique_type'),
        ('localisation', '0014_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='users.livreur'),
        ),
        migrations.AlterField(
            model_name='livraisonboutique',
            name='livreur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison_boutique', to='users.livreur'),
        ),
    ]
