# Generated by Django 4.2.25 on 2025-11-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0015_alter_livraison_livreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeboutique',
            name='prix_de_livraison',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commanderestaurant',
            name='prix_de_livraison',
            field=models.IntegerField(default=0),
        ),
    ]
