# Generated by Django 5.1.7 on 2025-10-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_boutique_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='type',
            field=models.CharField(default='supermarché', max_length=50),
        ),
    ]
