# Generated by Django 5.1.7 on 2025-10-31 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('cible', models.CharField(default='admin', max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
