# Generated by Django 5.2.7 on 2025-10-27 05:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MenuHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_hebdo', to='users.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=15)),
                ('menu_hebdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='e_commerce.menuhebdomadaire')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_statique', to='users.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('is_avialable', models.BooleanField(default=True)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.plat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'plat')},
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurants',
            field=models.ManyToManyField(related_name='plats', through='e_commerce.Restaurant_Plat', to='users.restaurant'),
        ),
        migrations.CreateModel(
            name='MenuStatique_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='aucune description')),
                ('prix', models.IntegerField()),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='e_commerce.menustatique')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.restaurant_plat')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='aucune description')),
                ('prix', models.IntegerField()),
                ('menu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_plat', to='e_commerce.menu')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.restaurant_plat')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='plats',
            field=models.ManyToManyField(related_name='menus', through='e_commerce.Menu_Plat', to='e_commerce.restaurant_plat'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('menu_hebdo', 'jour'), name='unique_menuhebdo_jour'),
        ),
    ]
